Capstone 1 - Chelmerrox Photography website
chelmerrox/capstone-1 pull request #1
Opened 2022-06-21 20:17 UTC by chelmerrox

Hi! This PR is for the Capstone 1 project. I've completed its requirements to:

- follow the design guidelines by Cindy Shin on Behance
- personalize my website
- create the mobile & desktop versions of the Home/main page & the About page
- create a responsive mobile menu when the hamburger icon is tapped in both pages
- dynamically create the Featured work sections on the Home/main page using JavaScript
- link the website logo to the home page 
- link the About link in Home page to About page

Thanks in advance for your review, comments & help!

<a href="https://www.loom.com/share/f70f99e9c9b74be790ab7e49c87690da">Link to my video presentation</a>

2022-06-22 17:28 UTC, Kossi-stack requested changes
## Hi @chelmerrox,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-22 17:28 UTC, Kossi-stack commented on index.html
> +          <div class="row section-2-1-1-mobile mb-3 py-3">
- [x] Kindly give the same size to your image so that all fit well.
![Capturecap](https://user-images.githubusercontent.com/81444338/175099716-2357aa6e-c139-4b3e-ba0a-305090407265.PNG)

2022-06-22 17:28 UTC, Kossi-stack commented on index.html
> +        <div class="section-4-1-desktop col-md-12 d-md-flex flex-md-row justify-content-ms-around mt-5 ps-5">
- [ ] Kindly fix the image.
![Capturecf](https://user-images.githubusercontent.com/81444338/175099978-75274143-4aba-4126-a3b1-9ac9e26b8432.PNG)

2022-06-22 22:23 UTC, Ismailco requested changes
#### Hi @chelmerrox,

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-22 22:23 UTC, Ismailco commented on index.html
> +          <div class="row section-2-1-1-mobile mb-3 py-3">
- [x] As the previous reviewer mentioned, kindly give all the cards the same (size) width so your design looks more e profissional

Your design looks like this for now 
![Screenshot_20220622_231113](https://user-images.githubusercontent.com/25227022/175161706-f1b4d771-03d6-4dd7-96b4-62031def9123.png)

2022-06-22 22:23 UTC, Ismailco commented on index.html
> +
- [x] [OPTIONAL] Kindly consider containing the headers of the `Photography Niche`, `Featured Work` and `Partners` with the orange `hr` so your design looks more apeling and aligns properly

![Screenshot_20220622_231801](https://user-images.githubusercontent.com/25227022/175162242-5ee43130-02ff-4f99-891d-6aca08f4ea31.png)

![Screenshot_20220622_231734](https://user-images.githubusercontent.com/25227022/175162217-1c241ecf-ded4-47c3-818b-46725215d88c.png)

![Screenshot_20220622_231748](https://user-images.githubusercontent.com/25227022/175162238-ef226b17-fdd2-4f41-9fe7-95d09d6f7906.png)

2022-06-22 22:23 UTC, Ismailco commented on styles/style.css
> +body {
- [x] [OPTIONAL] You can reduce the font size on your page so your design looks like the provided one

2022-06-23 10:46 UTC, Rustamxon7 approved these changes
## Hi @chelmerrox 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-06-23 11:51 UTC, merged